### PR TITLE
Follow-Up on "Do not call initializeObject from constructor"

### PR DESCRIPTION
**Pull request by Mabahe**

### CODE REVIEW

**Comment by garbast** [comment]
I do not agree with this patch. Merging the content of initializeObject in the constructor and removing the initializeObject method did lead to uninitialied properties, because the Container::getEmptyObject got an empty object from the instantiator after it used a reflectionClass with method newInstanceWithoutConstructor on isInstantiableViaReflection objects. See Doctrine\Instantiator\Instantiator::buildFactory

So a different solution is necessary.

**Comment by Mabahe** [comment]
ObjectManager->getEmptyObject (also doctrine/instantiator) is deprecated in v11; see:

https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Documentation/Changelog/11.3/Deprecation-94377-ExtbaseObjectManager-getEmptyObject.rst

https://github.com/TYPO3/typo3/blob/11.3/typo3/sysext/extbase/Classes/Object/ObjectManager.php#L123

Container is gone in v12 and Datamapper uses `makeInstance` in `createEmptyObject`
https://github.com/TYPO3/typo3/blob/main/typo3/sysext/extbase/Classes/Persistence/Generic/Mapper/DataMapper.php#L166

So for backwards compability` initializeObject` is still needed as fixed in 2b87f78. For v12 constructor initialisation is the way to go.

**Comment by garbast** [comment]
I'm aware that it is deprecated, but in 11.4 now getEmptyObject is still used in the DataMapper::mapSingleRow -> DataMapper::createEmptyObject -> $this->objectManager->getEmptyObject($className);. So for 11.4 compatibility we need to stick with initializeObject.

Forward looking DataMapper::createEmptyObject uses GeneralUtility::makeInstance($className). If we split 11.4 and > 12.1 branches We can get rid of initializeObject.

I keep the issue open for later implementation.

One word on the usage of resources inject* functions prodive. You could still use conditions that check if they are already present in initializeObject calls. So if the initializeObject function is called from constructor, i does not result in exceptions.

**Comment by Mabahe** [comment]
That's why I added initializeObject in 7fb5c31 (sorry wrong commit in last comment) again. Runs fine in production in 11.4. I've no other solution in my pocket, sorry. I remember an other extension does it like this,too. But I could not find it in time now.
In either case I can live with a patched extension.

**Comment by Mabahe** [comment]
Georgs solution in news
https://github.com/georgringer/news/blob/main/Classes/Domain/Model/News.php#L1035

**Pull request merged**
