### PR TITLE
[BUGFIX] Get current controller from GP since FrameworkConfiguration …

### PR DESCRIPTION
**Pull request by Schweriner**
…will get all possible controllers which makes it impossible to get the current validation-configuration

### CODE REVIEW

**Comment by garbast** [comment]
I dont know in which occasion this could happen, but i get a defined controllerConfiguration with only one controller available. How did you setup your registration?

**Comment by garbast** [comment]
auswahl_605

**Comment by Schweriner** [comment]
In TYPO3 8. Using the plugin for registration.

**Comment by garbast** [comment]
My screenshot was taken with TYPO3 8 and a plugin on a page with create selected in the plugin settings.

**Comment by Schweriner** [comment]
In TYPO3 8. Using the plugin for editing user data or password editing.

**Comment by Schweriner** [comment]
I've updated my comment. I had the problem inside the edit plugins. If you can't reproduce the problem, then maybe it was caused because I'm using flux, fluidpages, and fluidcontent and they are changing alot inside the runtime.

**Comment by garbast** [comment]
I turn this down for now. Feel free to come up with a different solution.

**Pull request closed without merging**
